In [6]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [7]:
df = pd.read_excel("home_prices.xlsx")
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
new_df = df.fillna(4)
new_df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [13]:
seconddf = new_df[['area', 'price']]
seconddf

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  595000
4  4000  760000

In [18]:
model = linear_model.LinearRegression()
model.fit(seconddf[['area']], seconddf.price)

LinearRegression()

In [19]:
model.coef_

array([134.07534247])

In [20]:
model.intercept_

176232.87671232875

In [24]:
model.predict([[3000]])

array([578458.90410959])

In [25]:
import pickle

In [27]:
#wb:write binary mode and we open a file
with open ('model_pickle','wb') as f:
    pickle.dump(model,f)

In [28]:
#rb:read binary mode
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [30]:
mp.predict([[3000]])

array([578458.90410959])

In [34]:
#joblib is more efficient for large numbers of numpy arrays:
import joblib

In [35]:
joblib.dump(model, 'model_joblib')

['model_joblib']

In [36]:
mj = joblib.load('model_joblib')

In [37]:
mj.predict([[3000]])

array([578458.90410959])